version: "3.9"
services:
  movie_rest:
    build: ./movie_rest/
    ports:
      - "5001:5001"
  movie2:
    build: ./movie_rest/
    ports:
      - "5002:5001"
  movie3:
    build: ./movie_rest/
    ports:
      - "5003:5001"
  movie4:
    build: ./movie_rest/
    ports:
      - "5004:5001"
  nginx:
    build: ./nginx/
    ports:
      - "8000:8000"
  movie_grpc:
    build: ./movie_grpc/
    ports:
      - "3001:3001"
  movie_graphql:
    build: ./movie_graphql/
    ports:
      - "3301:3301"
  plot_comparison:
    build: ./tests/
    depends_on:
      - movie_rest
      - movie_grpc
      - movie_graphql
    volumes:
      - ./results:/app/results
  nginx_test:
    build: ./nginx_test/
    depends_on:
      - nginx
